name: Deploy Test Backend


on:
  push:
    branches:
      - dev  # Ejecutar cuando haya un push en la rama dev


jobs:
  deploy:
    runs-on: ubuntu-latest


    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3


      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20


      # 3. Instalar dependencias del backend
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install


      # 4. Instalar dependencias del proyecto raíz
      - name: Install root dependencies
        run: npm install


      # 5. Esperar a que Mongo esté listo
      - name: Esperar a que Mongo esté listo
        run: |
          for i in {1..30}; do
            nc -z localhost 27017 && echo "Mongo está listo" && exit 0
            echo "Esperando a que Mongo esté listo..."
            sleep 2
          done
          echo "Mongo no se pudo iniciar" && exit 1


      # 6. Ejecutar tests
      - name: Run tests
        working-directory: ./server
        run: npm run test






