# -*- coding: utf-8 -*-
"""tiempos_greedy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnZ72xEv7D4aPJXWuyvX5ySnwX1keYcB
"""

# Librerias
import numpy as np
import matplotlib.pyplot as plt
import time
import sys

#Variables
things = int(sys.argv[1])  # Numero de objetos que tendrá la mochila
max_size = 500   # Tamaño maximo de la mochila
EPS = 0.001
weight = []     # Vector para los pesos
value = []      # Vector para los valores

# Inicializo tanto de los pesos como los valores de cada objeto de forma aleatoria
# dentro una cota
for i in range(things):
  weight.append((np.random.randint(1,max_size)))
  value.append(np.random.randint(1,100))

selected = []
cr = max_size # capacidad restante
i = 0
inicio = time.time()
while(i <= things and weight[i] <= cr):
  cr -= weight[i]
  selected.append(1)
  i += 1
fin = time.time()
duracion_greedy = fin-inicio
fichero = open("tiempos_greedy.txt", 'a')
fichero.write(str(duracion_greedy))
fichero.write("\n")
fichero.close()