# -*- coding: utf-8 -*-
"""tiempos_bb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCLMV4ykVu8FALKZrUnsOohED0T6zS-B
"""

import numpy as np
import matplotlib.pyplot as plt
import time
import sys

from ortools.linear_solver import pywraplp

#Variables
things = int(sys.argv[1])     # Numero de objetos que tendrá la mochila
max_size = 500  # Tamaño maximo de la mochila
EPS = 0.001
weight = []     # Vector para los pesos
value = []      # Vector para los valores

# Inicializo tanto de los pesos como los valores de cada objeto de forma aleatoria
# dentro una cota
for i in range(things):
  weight.append((np.random.randint(1,max_size)))
  value.append(np.random.randint(1,100))

solver = pywraplp.Solver('Problema de la mochila', pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)

# Creación de las variables
x = { i : solver.BoolVar('x[%i]' % i) for i in range(things)}  # Xij indica si la ruta desde i hasta j es tomada

# Función objetivo
solver.Maximize(solver.Sum(x[i]*value[i] for i in range(things)))

solver.Add(solver.Sum(x[i]*weight[i] for i in range(things)) <= max_size)

inicio = time.time()
status = solver.Solve()
fin = time.time()

duracion_bb = fin - inicio

fichero = open("tiempos_bb.txt", 'a')
fichero.write(str(duracion_bb))
fichero.write("\n")
fichero.close()